name: prepapp_3
description: "PrepApp — F-Droid (FLOSS only)"
publish_to: 'none'

environment:
  flutter: "3.24.3"
  sdk: ">=3.5.3 <4.0.0"

# versionName + versionCode (para F-Droid)
version: 1.0.5-fdroid+1000005

dependencies:
  flutter:
    sdk: flutter

  # MAPA 100% FOSS (substitui google_maps_flutter)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Localização / utilidades (todas FOSS)
  geolocator: ^13.0.2
  geocoding: ^2.1.0
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  url_launcher: ^6.3.1
  intl: ^0.19.0            # <- compatível com Dart 3.5.x
  http: ^1.2.2
  xml2json: ^5.3.1
  xml: ^6.5.0
  diacritic: ^0.1.3
  flutter_pdfview: ^1.2.7
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/banner.png
    - assets/bunqr_logo.png
    - assets/logo.png
  
